name = "my-sonicjs-app"
main = "src/index.ts"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
route = "dev2.clintonwentzel.com/*"
zone_id = "7668f14bcf5cf24ecc7792e6a0fccafe"

# Cloudflare account
account_id = "f9d6328dc3115e621758a741dda3d5c4"

# Cloudflare Workers settings
workers_dev = true

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "sonicjs-dev2-db"
database_id = "dc571fb3-65fb-4a0f-a24d-c3198aac886d"
migrations_dir = "./migrations"

# R2 Bucket for media storage
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "sonicjs-ci-media"

# KV Cache
[[kv_namespaces]]
binding = "CACHE_KV"
id = "a16f8246fc294d809c90b0fb2df6d363"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Observability
[observability]
enabled = true
